Feature POST /v1/orders
yanolja-finalproject/Backend pull request #107
Opened 2024-01-09 15:54 UTC by windowM

## ⭐ 개요
- 예약을 진행하는 기능
※ 현재는 `private static int dailyOrderCount = -1;` 을 사용해서 금일 order_code번호 초기화를 진행한다.

### 종류
- [ ] New Feature

### 📑 주요 작성/변경사항
- 예약진행시
  - 최대 인원수 체크
  - `Package` -> 구매 횟수 +1
  - `PackageDepartureOption` -> 현재 예약 인원  + order 예약인원

### 💡 특이 사항 
- packageId와 availableDateId의 관계를 확인하는 로직은 없습니다.
   ex). package A에 해당하는 availableDate의 id가 2,3,4,5라고 할지라도, availableDate=1로 들어와도 처리된다.
- 한 예약자가 실수로 두번 order를 하게 된거에 대한 처리가 없어도 되나?
- 
#### `OrderFacade`에 25~30 Line 중 하나라도 실패가 되면 rollback해줘야 하는데 적용시키기 위해 Transactional을 걸어주면 되나요?

### #️⃣ Issue Link - #56 

### Reference
<hr>

- 예약1 (정상)
![image](https://github.com/yanolja-finalproject/Backend/assets/87019291/fdc25d67-bc36-48dc-92ae-abb7cf2924fd)

<hr>

- 예약 2  (인원 초과)
![image](https://github.com/yanolja-finalproject/Backend/assets/87019291/6c632629-d13a-4947-9d63-0af4e885fb1a)

<hr>

- 날짜 변경에 따른 code 초기화
<가장 최근 order 1/9일 + code번호 확인>  // 이미지상은 아니지만 실제로 년도+월일도 바뀝니다!
![image](https://github.com/yanolja-finalproject/Backend/assets/87019291/2069dce6-941d-4e26-aabc-db95403cebf1)

<예약진행>
![image](https://github.com/yanolja-finalproject/Backend/assets/87019291/04a17afa-de8a-441b-b99b-13f17ac7d699)

<hr>

2024-01-09 15:56 UTC, windowM commented
테스트한다고 data.sql작업 브랜치를 poll해와서 그런가 섞였네요ㅠ

2024-01-10 01:29 UTC, deepredk requested changes
고생하셨습니다!

1. 서버가 껐다켜지면 dailyOrderCount가 다시 0부터 시작해 주문코드가 중복되는 문제
2. OrderFacade.create()의 내용이 꼭 트랜잭션으로 묶여야만 하는 부분인데 아직 따로 트랜잭션을 묶이지 않은 문제

이 두 가지 문제는 꼭 해결이 되어야 할 것 같아 Request changes로 남깁니다

2024-01-10 01:29 UTC, deepredk commented on src/main/java/com/yanolja_final/domain/order/exception/MaximumCapacityReachedException.java
> +        super(ErrorCode.MAXIMUN_CAPACITY);
Reached => Exceeded가 되어야 의미가 제대로 전달될 것 같습니다

2024-01-10 01:29 UTC, deepredk commented on src/main/java/com/yanolja_final/domain/order/service/OrderService.java
> +            today.getYear(), today.getMonthValue(), today.getDayOfMonth(), ++dailyOrderCount);
이렇게 하면 서버가 껐다 켜지면 dailyOrderCount가 다시 0부터 시작해 문제가 발생할 것 같습니다

2024-01-10 01:29 UTC, deepredk commented on src/main/java/com/yanolja_final/domain/user/service/UserService.java
> +    }
assertNotDeleted 등이 더 적절할 것 같습니다
지금 메서드 이름은 boolean을 반환할 것 같이 생겨서요

2024-01-10 01:29 UTC, deepredk commented on src/main/java/com/yanolja_final/domain/order/facade/OrderFacade.java
> +    }
여기 트랜잭션 묶여야 할 것 같습니다
근데 Facade에 `@Transactional` 붙여도 예외 전파 잘 되는지 저도 잘 모르겠어요..
오늘 멘토님께 여쭤봐야 할 것 같습니다

2024-01-10 01:31 UTC, deepredk commented
packageId와 availableDateId의 관계를 확인하는 로직은 없습니다.
ex). package A에 해당하는 availableDate의 id가 2,3,4,5라고 할지라도, availableDate=1로 들어와도 처리된다.
=> 이 관계 확인하는 로직은 무조건 필요할 것 같습니다

한 예약자가 실수로 두번 order를 하게 된거에 대한 처리가 없어도 되나?
=> 실수로 했는지 고의로 했는지 판단할 수 없으므로 처리도 하지 못한다고 생각합니다

2024-01-10 01:36 UTC, windowM commented on src/main/java/com/yanolja_final/domain/order/service/OrderService.java
> +            today.getYear(), today.getMonthValue(), today.getDayOfMonth(), ++dailyOrderCount);
네.. 꼭 서버를 끄지 않아도 다중 서버만 둬도 사실 문제가 되는 코드죠... 
금일 멘토링때 여쭤보고 수정하겠습니다!

2024-01-10 01:41 UTC, windowM commented
@deepredk 
packageId와 availableDateId의 관계를 확인하는 로직은 없습니다.
ex). package A에 해당하는 availableDate의 id가 2,3,4,5라고 할지라도, availableDate=1로 들어와도 처리된다.
=> 이 관계 확인하는 로직은 무조건 필요할 것 같습니다

Q. packageId로 PackageDepartureOption에서 데이터들을 찾고 그 중 availableDateId가 있는지 정도로 확인하면 될까요?

2024-01-10 01:42 UTC, deepredk commented
@windowM 
availableDate 테이블에 package_id 컬럼이 있으니
dateId = 100, package_id = 200이라치면

id=100인 availableDate 행에 package_id 컬럼이 200이 맞는지만 확인해도 충분하지 않을까요?

2024-01-10 08:31 UTC, deepredk commented on src/main/java/com/yanolja_final/global/exception/ErrorCode.java
> +    MAXIMUN_CAPACITY(HttpStatus.BAD_REQUEST, "허용인원이 초과되었습니다."),
'허용인원'이라는 단어는 프론트엔드분 입장에서 이해하기 어려울 수 있을 것 같습니다
허용인원 => 예약 인원 어떨까요

2024-01-15 02:55 UTC, deepredk approved these changes
고생하셨습니다! 👍👍

2024-01-15 03:07 UTC, JeongByungJoo approved these changes
저에게는 새로운 로직이 많아서 살펴볼 부분이 많네요,
수고 많으셨습니다!

2024-01-15 05:12 UTC, ghrltjdtprbs approved these changes
확인했습니다! 고생많으셨어요!! 코드 충돌나는 부분이 있으니 그 부분만 해결하시면 될 것 같습니다! 👍👍

2024-01-15 09:50 UTC, deepredk commented
리베이스 및 충돌 해결하느라  고생 많으셨습니다

2024-01-18 20:49 UTC, merged