[Feature] 내 정보 수정 PATCH v1/my/info #39
yanolja-finalproject/Backend pull request #121
Opened 2024-01-12 05:48 UTC by JeongByungJoo

## ⭐ 테스트 결과 사진

![MyPage_update_전라도 여수](https://github.com/yanolja-finalproject/Backend/assets/129931655/84a42010-172a-44d2-ae45-6aa5eab14c3b)

![MyPage_update_부산광역시 해운대구](https://github.com/yanolja-finalproject/Backend/assets/129931655/adea1753-2726-4768-823f-b17d4aab5843)

![MyPage_update_부산 광역시 서구](https://github.com/yanolja-finalproject/Backend/assets/129931655/82ecf345-193b-4488-af67-930190ca1d76)

![MyPage_GetUserInfo_부산 광역시 서구](https://github.com/yanolja-finalproject/Backend/assets/129931655/46897170-4c73-4b53-8cfc-6882fd75ba05)

### 📑 주요 작성/변경사항
PATCH를 활용 - Request에 요청된 필드의 값 중 null이 아닌 값에 한해서만 업데이트 하는 기능 추가

2024-01-12 07:44 UTC, deepredk requested changes
고생하셨습니다!
피드백 남겼으니 확인하시고 반영 부탁드립니다

2024-01-12 07:44 UTC, deepredk commented on src/main/java/com/yanolja_final/domain/user/dto/request/UpdateMyPageRequest.java
> +    }
이 코드는 어떤 부분 때문에 넣으신건가요?

2024-01-12 07:44 UTC, deepredk commented on src/main/java/com/yanolja_final/domain/user/dto/request/UpdateMyPageRequest.java
> +    }
setter는 일반적으로 정말 필요한 것이 아닌 이상 권장되지 않습니다.
이쪽에서 user.set을 일일이 하기보다
User 엔티티에 update(String phone, addr1, addr2, postCode) 메서드를 만드는 방향을 추천드립니다

2024-01-12 10:54 UTC, JeongByungJoo commented on src/main/java/com/yanolja_final/domain/user/dto/request/UpdateMyPageRequest.java
> +    }
해당 코드는 API 설계도에 있는 내용 중 000-0000-0000 으로 형식을 나오게 해야 한다는 것을 보고
일반 숫자를 넣어도 해당 형식 모양으로 바뀌어 나오도록 추가했었습니다.

2024-01-12 10:55 UTC, JeongByungJoo commented on src/main/java/com/yanolja_final/domain/user/dto/request/UpdateMyPageRequest.java
> +    }
아! 처음엔 해당 방법으로 진행을 했었는데, 편해 보이는 방향으로 진행을 했었거든요,
setter 관련 내용 피드백 반영해서 수정해서 올려보도록 하겠습니다!

2024-01-13 01:40 UTC, JeongByungJoo commented on src/main/java/com/yanolja_final/domain/user/dto/request/UpdateMyPageRequest.java
> +    }
피드백 주신대로 Request에서 검증하는 부분 넣어두었습니다.
![image](https://github.com/yanolja-finalproject/Backend/assets/129931655/2deb1aeb-d075-449b-bc7c-f44f7b0ee1b0)

2024-01-13 01:42 UTC, JeongByungJoo commented on src/main/java/com/yanolja_final/domain/user/dto/request/UpdateMyPageRequest.java
> +    }
![image](https://github.com/yanolja-finalproject/Backend/assets/129931655/bd4d48f7-6e59-4e38-b392-c8ca8f41b6f2)
User에 로직 추가하였고, 해당 내용 관련해서 request에서 가져오는 해당 필드 값 사용하도록 Service로직 변경했습니다. 
![image](https://github.com/yanolja-finalproject/Backend/assets/129931655/d44c83d5-207c-47e7-8332-7082743ed6da)

2024-01-13 01:48 UTC, JeongByungJoo commented
## 수정 후 테스트 사진 다시 첨부합니다.
### <휴대폰 Validation , Request에서 검>
![MyPage_null_값](https://github.com/yanolja-finalproject/Backend/assets/129931655/7f7938d5-44ad-423e-9ef5-88eaf0ee990d)
![MyPage_Phone_InvalidForm](https://github.com/yanolja-finalproject/Backend/assets/129931655/4dd0ef21-339d-4c27-aa53-3187753751f6)

### <휴대폰만 형식에 맞는 값 넣고, 나머진 전부 "">
![MyPage_핸드폰 번호만](https://github.com/yanolja-finalproject/Backend/assets/129931655/f509af5b-6021-443a-936f-3355a66023e3)
![MyPage_H2_핸드폰번호](https://github.com/yanolja-finalproject/Backend/assets/129931655/cafc78f1-9e8d-49f4-9123-027e04ee7271)

###<울릉도 지역 업데이트>
![MyPage_울릉도](https://github.com/yanolja-finalproject/Backend/assets/129931655/74459e1b-519a-49d9-a772-191cb42936c4)
![MyPage_H2_울릉도](https://github.com/yanolja-finalproject/Backend/assets/129931655/057c552c-7e65-4d23-88c6-27b7bc49f141)

### <이 외 수정사항>
: ResponseDTO Service와 Facade에서 전부 제거하고 Controller로 옮겼습니다.

2024-01-13 05:01 UTC, deepredk commented on src/main/java/com/yanolja_final/domain/user/dto/request/UpdateMyPageRequest.java
> +    @Pattern(regexp = "\\d{3}-\\d{4}-\\d{4}", message = " 010-0000-0000 형식으로 입력해주세요 ")
👍👍👍👍👍

2024-01-13 05:02 UTC, deepredk commented on src/main/java/com/yanolja_final/domain/user/dto/request/UpdateMyPageRequest.java
> +    }
확인했습니다! 제가 생각한 그대로 작업해주셨네요

2024-01-13 05:04 UTC, deepredk approved these changes
Git 커밋이 뭔가 꼬인건지 Faq랑 Notice가 섞여서 나오네요
피드백 반영해주신 것 확인했습니다 고생하셨습니다 👍

2024-01-13 05:25 UTC, JeongByungJoo commented on src/main/java/com/yanolja_final/domain/user/dto/request/UpdateMyPageRequest.java
> +    @Pattern(regexp = "\\d{3}-\\d{4}-\\d{4}", message = " 010-0000-0000 형식으로 입력해주세요 ")
다음엔 Commit도 확인해볼 수 있도록 노력해보겠습니다

2024-01-14 14:34 UTC, ghrltjdtprbs approved these changes
수고하셨습니다! 😊😊

2024-01-15 05:15 UTC, merged