Feature/36
yanolja-finalproject/Backend pull request #156
Opened 2024-01-21 03:34 UTC by JeongByungJoo

## ⭐ 개요
주문한 패키지 상품 중 departureDate를 기준으로 가장 가까운 패키지 조회

### 종류
- [x] New Feature

### 📑 주요 작성/변경사항
- [마이 페이지 -> 다가오는 패키지 조회]
- [OrderService와 PackageService MyPageFacade에서 참조 활용]

### 사진 첨부
<다가오는 패키지 비교 조회 결과 사진>
![UpcomingPackage_Malaysia_ComparisonPhoto](https://github.com/yanolja-finalproject/Backend/assets/129931655/f9ba6083-971d-4e5c-8a53-63775fbfb027)

<마이 페이지 get 조회 및 오더 get 조회 중 날짜 비교 사진>
![UpcomingPackage_20240121](https://github.com/yanolja-finalproject/Backend/assets/129931655/e37967ae-6651-4431-b302-709b3264f3a1)

<H2 사진>
![UpcomingPackage_H2_20240121](https://github.com/yanolja-finalproject/Backend/assets/129931655/f551811e-5e57-4740-9445-d0572768293a)

<말레이시아 패키지 조회 전체 사진>
![UpcomingPackage_Malaysia](https://github.com/yanolja-finalproject/Backend/assets/129931655/c0a8b2d7-bd44-4a5b-9edf-79f0a5dd5a33)

<베트남 패키지 조회 전체 사진>
![UpcomingPackage_Vietnam](https://github.com/yanolja-finalproject/Backend/assets/129931655/d05c6d9d-07b4-412b-85f5-bcef53b630d1)

2024-01-21 05:40 UTC, deepredk requested changes
_XXXService에서는 XXXRepository만 참조하셔야 됩니다_
이 부분이 아마 피드백 반영하시기 제일 까다로우실 것 같습니다

2024-01-21 05:40 UTC, deepredk commented on src/main/java/com/yanolja_final/domain/order/service/OrderService.java
> +    private final UserRepository userRepository;
XXXService에서는 XXXRepository만 참조하셔야 합니다

2024-01-21 05:40 UTC, deepredk commented on src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
> +    }
이 메서드는 Service에 두기보다 PackageDepartureOption 클래스에 두는 게 적절할 것 같습니다

2024-01-21 05:40 UTC, deepredk commented on src/main/java/com/yanolja_final/domain/user/facade/MyPageFacade.java
> +        User user = userId == null ? null : myPageService.findById(userId);
변수가 선언되고 쓰이지 않고 있습니다

2024-01-21 06:05 UTC, deepredk commented on src/main/java/com/yanolja_final/domain/order/service/OrderService.java
> +    }
이건 Order에 availableDate(departureoption)을 @OneToOne JPA 매핑 걸고 
Order 메서드로 넣어도 괜찮을 것 같네요

2024-01-22 02:23 UTC, JeongByungJoo commented on src/main/java/com/yanolja_final/domain/order/service/OrderService.java
> +    private final UserRepository userRepository;
관련 내용 참고해서 수정해보도록 하겠습니다!

2024-01-22 02:25 UTC, JeongByungJoo commented on src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
> +    }
위치도 고민 많이 했었는데, 피드백 전부 확인했고, 틀을 잡아주시니 거기에 맞게 수정이 가능할 것 같습니다. 수정해보도록 하겠습니다.

2024-01-22 16:29 UTC, closed without merging